/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'XxX' at '12/13/16 10:42 PM' with Gradle 2.13
 *
 * @author XxX, @date 12/13/16 10:42 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
